# Generated by Django 3.1.3 on 2020-11-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_time', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market_time',
            name='close',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='market_time',
            name='open',
            field=models.TimeField(),
        ),
    ]
