# Generated by Django 3.1.3 on 2020-11-20 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country_time', '0002_auto_20201119_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market_time',
            old_name='close',
            new_name='close_time',
        ),
        migrations.RenameField(
            model_name='market_time',
            old_name='open',
            new_name='open_time',
        ),
    ]
