# Generated by Django 3.1.3 on 2020-11-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_time', '0003_auto_20201120_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market_time',
            name='close_time',
            field=models.TimeField(verbose_name='%H:%M'),
        ),
        migrations.AlterField(
            model_name='market_time',
            name='open_time',
            field=models.TimeField(verbose_name='%H:%M'),
        ),
    ]
