# Generated by Django 3.1.3 on 2020-11-20 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country_time', '0006_auto_20201120_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market_time',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='market_time',
            name='open_time',
        ),
    ]
