# Generated by Django 3.1.3 on 2020-11-20 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('country_time', '0007_auto_20201120_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='market_time',
            name='open_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
