# Generated by Django 3.1.3 on 2020-11-20 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('country_time', '0008_market_time_open_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='market_time',
            name='close_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
