# Generated by Django 3.1.1 on 2020-11-22 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('minDeposit', models.IntegerField()),
                ('bankTransfer', models.CharField(max_length=20)),
                ('withdrawlFee', models.CharField(max_length=20)),
                ('negBalProtection', models.CharField(max_length=20)),
                ('rating', models.IntegerField()),
                ('benefit', models.CharField(max_length=200)),
                ('platformSup', models.CharField(max_length=200)),
                ('accounts', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Spread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inrUsd', models.FloatField()),
                ('inrEuro', models.FloatField()),
                ('inrJap', models.FloatField()),
                ('inrCan', models.FloatField()),
                ('inrAus', models.FloatField()),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex.trader')),
            ],
        ),
    ]
