# Generated by Django 3.0.8 on 2020-11-23 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='forex_hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50)),
                ('open_time', models.TextField()),
                ('close_time', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('minDeposit', models.IntegerField()),
                ('bankTransfer', models.CharField(max_length=20)),
                ('withdrawlFee', models.CharField(max_length=20)),
                ('negBalProtection', models.CharField(max_length=20)),
                ('rating', models.IntegerField()),
                ('benefit', models.CharField(max_length=200)),
                ('platformSup', models.CharField(max_length=200)),
                ('accounts', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Spread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INRUSD', models.FloatField()),
                ('INREUR', models.FloatField()),
                ('INRJPY', models.FloatField()),
                ('INRCAD', models.FloatField()),
                ('INRAUD', models.FloatField()),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex.Trader')),
            ],
        ),
    ]
