# Generated by Django 3.1.1 on 2020-11-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spread',
            old_name='inrAus',
            new_name='INRAUD',
        ),
        migrations.RenameField(
            model_name='spread',
            old_name='inrCan',
            new_name='INRCAD',
        ),
        migrations.RenameField(
            model_name='spread',
            old_name='inrEuro',
            new_name='INREUR',
        ),
        migrations.RenameField(
            model_name='spread',
            old_name='inrJap',
            new_name='INRJPY',
        ),
        migrations.RenameField(
            model_name='spread',
            old_name='inrUsd',
            new_name='INRUSD',
        ),
    ]
